version: "3.7"

services:
  # ---------- Moleculer default containers ----------

  api:
      build:
        context: .
        dockerfile: ./Dockerfile_dev
      image: api
      restart: on-failure
      env_file: docker-compose_dev.env
      volumes:
        - ./services:/app/services:delegated
      environment:
        SERVICES: api,assets
        # SERVICES: api
        PORT: 3001
      depends_on:
        - rabbitMQ
      labels:
        - "traefik.enable=true"
        - "traefik.backend=api"
        - "traefik.port=3001"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=PathPrefix:/"
      networks:
        microServiceNetwork:
          ipv4_address: 172.28.0.4

  rabbitMQ:
      image: rabbitmq:3.7.16-rc.3-management-alpine
      ports:
        - "5672:5672"
      restart: on-failure
      networks:
        microServiceNetwork:
          ipv4_address: 172.28.0.3

  traefik:
      image: traefik:alpine
      command: --web --docker --docker.domain=docker.localhost --docker.exposedbydefault=false
      restart: on-failure
      ports:
        - "3001:80"
        - "3004:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml
      networks:
        microServiceNetwork:
          ipv4_address: 172.28.0.2

networks:
  microServiceNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16